CREATE DATABASE MySeat_DB;

# SEAT ID SAMPLE A01,A10,G17 AND SO ON
CREATE TABLE SEAT_VALUES_TBL (
	
	ID VARCHAR(3) PRIMARY KEY,
	VALUE INT NOT NULL,
	CUSTOMER_ID VARCHAR(50) NOT NULL
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_TBL(ID)
);	
# ID EXAMPLE ANI IS 50 CHARACTER NGA GI RANDOMIZED PERO UNIQUE MANGITA RAKO OG ALGO PARA ANI.
CREATE TABLE COSTUMER_TBL(
	
	ID VARCHAR (50) PRIMARY KEY 
	
	
);